apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: default
  namespace: istio-system
spec:
  tracing:
  - disableSpanReporting: true
  accessLogging:
  - disabled: true
  metrics:
    overrides:
    - disabled: true